/* ISO 4217 currencies. Loaded by the browser (global `CURRENCIES`) and by node. */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) { module.exports = factory(); }
  else { root.CURRENCIES = factory(); }
})(typeof self !== 'undefined' ? self : this, function () {
  return [
  { code: "AED", name: "UAE Dirham", symbol: "د.إ", decimals: 2 },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋", decimals: 2 },
  { code: "ALL", name: "Albanian Lek", symbol: "L", decimals: 2 },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", decimals: 2 },
  { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ", decimals: 2 },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", decimals: 2 },
  { code: "ARS", name: "Argentine Peso", symbol: "AR$", decimals: 2 },
  { code: "AUD", name: "Australian Dollar", symbol: "A$", decimals: 2 },
  { code: "AWG", name: "Aruban Florin", symbol: "ƒ", decimals: 2 },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", decimals: 2 },
  { code: "BAM", name: "Bosnian Convertible Mark", symbol: "KM", decimals: 2 },
  { code: "BBD", name: "Barbadian Dollar", symbol: "Bds$", decimals: 2 },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", decimals: 2 },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", decimals: 2 },
  { code: "BHD", name: "Bahraini Dinar", symbol: "BD", decimals: 3 },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu", decimals: 0 },
  { code: "BMD", name: "Bermudian Dollar", symbol: "BD$", decimals: 2 },
  { code: "BND", name: "Brunei Dollar", symbol: "B$", decimals: 2 },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs.", decimals: 2 },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", decimals: 2 },
  { code: "BSD", name: "Bahamian Dollar", symbol: "B$", decimals: 2 },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", decimals: 2 },
  { code: "BWP", name: "Botswana Pula", symbol: "P", decimals: 2 },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", decimals: 2 },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$", decimals: 2 },
  { code: "CAD", name: "Canadian Dollar", symbol: "CA$", decimals: 2 },
  { code: "CDF", name: "Congolese Franc", symbol: "FC", decimals: 2 },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF ", decimals: 2 },
  { code: "CLP", name: "Chilean Peso", symbol: "CLP$", decimals: 0 },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥", decimals: 2 },
  { code: "COP", name: "Colombian Peso", symbol: "COL$", decimals: 2 },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡", decimals: 2 },
  { code: "CUP", name: "Cuban Peso", symbol: "₱", decimals: 2 },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "Esc", decimals: 2 },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", decimals: 2 },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj", decimals: 0 },
  { code: "DKK", name: "Danish Krone", symbol: "kr ", decimals: 2 },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", decimals: 2 },
  { code: "DZD", name: "Algerian Dinar", symbol: "DA", decimals: 2 },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£", decimals: 2 },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", decimals: 2 },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", decimals: 2 },
  { code: "EUR", name: "Euro", symbol: "€", decimals: 2 },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$", decimals: 2 },
  { code: "FKP", name: "Falkland Islands Pound", symbol: "£", decimals: 2 },
  { code: "GBP", name: "British Pound", symbol: "£", decimals: 2 },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", decimals: 2 },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "GH₵", decimals: 2 },
  { code: "GIP", name: "Gibraltar Pound", symbol: "£", decimals: 2 },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", decimals: 2 },
  { code: "GNF", name: "Guinean Franc", symbol: "FG", decimals: 0 },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", decimals: 2 },
  { code: "GYD", name: "Guyanese Dollar", symbol: "G$", decimals: 2 },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", decimals: 2 },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", decimals: 2 },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn", decimals: 2 },
  { code: "HTG", name: "Haitian Gourde", symbol: "G", decimals: 2 },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", decimals: 2 },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", decimals: 2 },
  { code: "ILS", name: "Israeli New Shekel", symbol: "₪", decimals: 2 },
  { code: "INR", name: "Indian Rupee", symbol: "₹", decimals: 2 },
  { code: "IQD", name: "Iraqi Dinar", symbol: "IQD ", decimals: 3 },
  { code: "IRR", name: "Iranian Rial", symbol: "IRR ", decimals: 2 },
  { code: "ISK", name: "Icelandic Króna", symbol: "kr ", decimals: 0 },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$", decimals: 2 },
  { code: "JOD", name: "Jordanian Dinar", symbol: "JD", decimals: 3 },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", decimals: 0 },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", decimals: 2 },
  { code: "KGS", name: "Kyrgyzstani Som", symbol: "с", decimals: 2 },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", decimals: 2 },
  { code: "KMF", name: "Comorian Franc", symbol: "CF", decimals: 0 },
  { code: "KPW", name: "North Korean Won", symbol: "₩", decimals: 2 },
  { code: "KRW", name: "South Korean Won", symbol: "₩", decimals: 0 },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "KD", decimals: 3 },
  { code: "KYD", name: "Cayman Islands Dollar", symbol: "CI$", decimals: 2 },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", decimals: 2 },
  { code: "LAK", name: "Lao Kip", symbol: "₭", decimals: 2 },
  { code: "LBP", name: "Lebanese Pound", symbol: "L£", decimals: 2 },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", decimals: 2 },
  { code: "LRD", name: "Liberian Dollar", symbol: "L$", decimals: 2 },
  { code: "LSL", name: "Lesotho Loti", symbol: "L", decimals: 2 },
  { code: "LYD", name: "Libyan Dinar", symbol: "LD", decimals: 3 },
  { code: "MAD", name: "Moroccan Dirham", symbol: "MAD ", decimals: 2 },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", decimals: 2 },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", decimals: 2 },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден", decimals: 2 },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K", decimals: 2 },
  { code: "MNT", name: "Mongolian Tögrög", symbol: "₮", decimals: 2 },
  { code: "MOP", name: "Macanese Pataca", symbol: "MOP$", decimals: 2 },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM", decimals: 2 },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨", decimals: 2 },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", decimals: 2 },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK", decimals: 2 },
  { code: "MXN", name: "Mexican Peso", symbol: "MX$", decimals: 2 },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", decimals: 2 },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT", decimals: 2 },
  { code: "NAD", name: "Namibian Dollar", symbol: "N$", decimals: 2 },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", decimals: 2 },
  { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", decimals: 2 },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr ", decimals: 2 },
  { code: "NPR", name: "Nepalese Rupee", symbol: "Rs", decimals: 2 },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", decimals: 2 },
  { code: "OMR", name: "Omani Rial", symbol: "OMR ", decimals: 3 },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", decimals: 2 },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/", decimals: 2 },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", decimals: 2 },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", decimals: 2 },
  { code: "PKR", name: "Pakistani Rupee", symbol: "Rs", decimals: 2 },
  { code: "PLN", name: "Polish Złoty", symbol: "zł", decimals: 2 },
  { code: "PYG", name: "Paraguayan Guaraní", symbol: "₲", decimals: 0 },
  { code: "QAR", name: "Qatari Riyal", symbol: "QR", decimals: 2 },
  { code: "RON", name: "Romanian Leu", symbol: "lei", decimals: 2 },
  { code: "RSD", name: "Serbian Dinar", symbol: "din", decimals: 2 },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", decimals: 2 },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw", decimals: 0 },
  { code: "SAR", name: "Saudi Riyal", symbol: "SR", decimals: 2 },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "SI$", decimals: 2 },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨", decimals: 2 },
  { code: "SDG", name: "Sudanese Pound", symbol: "SDG ", decimals: 2 },
  { code: "SEK", name: "Swedish Krona", symbol: "kr ", decimals: 2 },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", decimals: 2 },
  { code: "SHP", name: "Saint Helena Pound", symbol: "£", decimals: 2 },
  { code: "SLE", name: "Sierra Leonean Leone", symbol: "Le", decimals: 2 },
  { code: "SOS", name: "Somali Shilling", symbol: "Sh", decimals: 2 },
  { code: "SRD", name: "Surinamese Dollar", symbol: "Sr$", decimals: 2 },
  { code: "SSP", name: "South Sudanese Pound", symbol: "SSP ", decimals: 2 },
  { code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db", decimals: 2 },
  { code: "SVC", name: "Salvadoran Colón", symbol: "₡", decimals: 2 },
  { code: "SYP", name: "Syrian Pound", symbol: "S£", decimals: 2 },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "E", decimals: 2 },
  { code: "THB", name: "Thai Baht", symbol: "฿", decimals: 2 },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "SM", decimals: 2 },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "T", decimals: 2 },
  { code: "TND", name: "Tunisian Dinar", symbol: "DT", decimals: 3 },
  { code: "TOP", name: "Tongan Paʻanga", symbol: "T$", decimals: 2 },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", decimals: 2 },
  { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$", decimals: 2 },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$", decimals: 2 },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", decimals: 2 },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", decimals: 2 },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh", decimals: 0 },
  { code: "USD", name: "US Dollar", symbol: "$", decimals: 2 },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", decimals: 2 },
  { code: "UZS", name: "Uzbekistani Som", symbol: "soʻm", decimals: 2 },
  { code: "VES", name: "Venezuelan Bolívar", symbol: "Bs.", decimals: 2 },
  { code: "VND", name: "Vietnamese Đồng", symbol: "₫", decimals: 0 },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "VT", decimals: 0 },
  { code: "WST", name: "Samoan Tala", symbol: "WS$", decimals: 2 },
  { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA", decimals: 0 },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "EC$", decimals: 2 },
  { code: "XOF", name: "West African CFA Franc", symbol: "CFA", decimals: 0 },
  { code: "XPF", name: "CFP Franc", symbol: "₣", decimals: 0 },
  { code: "YER", name: "Yemeni Rial", symbol: "YER ", decimals: 2 },
  { code: "ZAR", name: "South African Rand", symbol: "R", decimals: 2 },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", decimals: 2 },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "Z$", decimals: 2 }
  ];
});
